var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-1,"undefined1");
subject.inc(-1,undefined);
subject.inc(0,"undefined1");
subject.inc(0,undefined);
subject.weird(8,-1,41,"strict1");
subject.weird(8,-1,41,"strict");
subject.weird(8,-1,41,"werw");
subject.weird(8,-1,41,"");
subject.weird(8,-1,42,"strict1");
subject.weird(8,-1,42,"strict");
subject.weird(8,-1,42,"werw");
subject.weird(8,-1,42,"");
subject.weird(8,0,41,"strict1");
subject.weird(8,0,41,"strict");
subject.weird(8,0,41,"werw");
subject.weird(8,0,41,"");
subject.weird(8,0,42,"strict1");
subject.weird(8,0,42,"strict");
subject.weird(8,0,42,"werw");
subject.weird(8,0,42,"");
subject.weird(7,-1,41,"strict1");
subject.weird(7,-1,41,"strict");
subject.weird(7,-1,41,"werw");
subject.weird(7,-1,41,"");
subject.weird(7,-1,42,"strict1");
subject.weird(7,-1,42,"strict");
subject.weird(7,-1,42,"werw");
subject.weird(7,-1,42,"");
subject.weird(7,0,41,"strict1");
subject.weird(7,0,41,"strict");
subject.weird(7,0,41,"werw");
subject.weird(7,0,41,"");
subject.weird(7,0,42,"strict1");
subject.weird(7,0,42,"strict");
subject.weird(7,0,42,"werw");
subject.weird(7,0,42,"");
mock({"path/fileExists":{},"pathContent":{"file1":"text content"},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('nonEmptyPath','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('nonEmptyPath','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('nonEmptyPath','pathContent/file1');
mock.restore();
mock({"pathContent":{"file2":""}});
	subject.fileTest('nonEmptyPath','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('nonEmptyPath','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('nonEmptyPath','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""},"nonEmptyPath":{"some-file.txt":"file content here"}});
	subject.fileTest('nonEmptyPath','pathContent/file2');
mock.restore();
mock({"pathContent":{"file2":""}});
	subject.fileTest('nonEmptyPath','pathContent/file2');
mock.restore();
subject.normalize('1-039-565-1602');
subject.format('(302) 212-3327','(302) 212-3327',{"normalize":true});
subject.format('(302) 212-3327','(302) 212-3327',{"normalize":false});
subject.blackListNumber("277-394-6760");
subject.blackListNumber("212-394-6760");
