var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-1,undefined);
subject.inc(-1,"undefined1");
subject.inc(0,undefined);
subject.inc(0,"undefined1");
subject.weird(8,-1,41,"strict");
subject.weird(8,-1,41,"strict1");
subject.weird(8,-1,41,"werw");
subject.weird(8,-1,41,"");
subject.weird(8,-1,42,"strict");
subject.weird(8,-1,42,"strict1");
subject.weird(8,-1,42,"werw");
subject.weird(8,-1,42,"");
subject.weird(8,0,41,"strict");
subject.weird(8,0,41,"strict1");
subject.weird(8,0,41,"werw");
subject.weird(8,0,41,"");
subject.weird(8,0,42,"strict");
subject.weird(8,0,42,"strict1");
subject.weird(8,0,42,"werw");
subject.weird(8,0,42,"");
subject.weird(7,-1,41,"strict");
subject.weird(7,-1,41,"strict1");
subject.weird(7,-1,41,"werw");
subject.weird(7,-1,41,"");
subject.weird(7,-1,42,"strict");
subject.weird(7,-1,42,"strict1");
subject.weird(7,-1,42,"werw");
subject.weird(7,-1,42,"");
subject.weird(7,0,41,"strict");
subject.weird(7,0,41,"strict1");
subject.weird(7,0,41,"werw");
subject.weird(7,0,41,"");
subject.weird(7,0,42,"strict");
subject.weird(7,0,42,"strict1");
subject.weird(7,0,42,"werw");
subject.weird(7,0,42,"");
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('(182) 252-2277 x47418');
subject.format('(803) 057-1523','(803) 057-1523','(803) 057-1523');
subject.blackListNumber('1-952-537-4161 x4281');
